# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml

homematic:
  interfaces:
    rf:
      host: !secret homematic_host
      resolvenames: json
      username: !secret homatic_username
      password: !secret homatic_password

binary_sensor:
  - platform: workday
    country: !secret workday_country
    province: !secret workday_province

sensor: 
  - platform: template
    sensors:
      v_last_reboot:
        value_template: "{{ state_attr('homematic.ccu3', 'V_Last_Reboot') or '01.01.1970 00:00:00' }}"
        icon_template: "mdi:clock"
        entity_id: homematic.ccu3

pi_hole:
  host: !secret pi-hole_host
  monitored_conditions:
    - ads_blocked_today
    - dns_queries_today
    - unique_clients

http:
  base_url: !secret http_base_url # the Home Assistant https url which is exposed to the internet.

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_api_key
    parse_mode: markdown
    allowed_chat_ids:
      - !secret telegram_chat_id_1

camera:
  - platform: foscam
    ip: !secret foscam_ip
    port: !secret foscam_port
    username: !secret foscam_username
    password: !secret foscam_password
